### ISSUE TITLE
start-ovs-deb.sh doesn't exists anymore

### ISSUE THREAD

**Issue by pbandzi** [alagalah/gbpsfc-env#11]
Hi Keith,

Do you remember what was in this script? It suppose to start from ovsinstall.sh.
But https://raw.githubusercontent.com/priteshk/ovs/nsh-v8/third-party/start-ovs-deb.sh is not found.

thanks, 
Peter

**Comment by alagalah** [comment]
Apparently there are some issues with the repo. The owner is sorting it out, but in the interim, I will be publishing a box file for handling this. Look for email to groupbasedpolicy-dev later today.

**Comment by pbandzi** [comment]
it's working now
